// <auto-generated />
using DataLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebLayer.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250307152854_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DataLayer.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "iyi telefon",
                            Name = "Samsung s24",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "iyi telefon",
                            Name = "Samsung s25",
                            Price = 20300m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "iyi telefon",
                            Name = "Samsung s26",
                            Price = 50300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
